export const STORAGE_KEY_PREFIX = "dsanotes";

export const MESSAGE_TYPES = {
    QUESTION_CHANGED: "QUESTION_CHANGED",
    TOGGLE_PANEL: "TOGGLE_PANEL",
    GET_NOTE: "GET_NOTE",
    SAVE_NOTE: "SAVE_NOTE"
};